dubbo:
  application:
    name: nim-service
  registry:
    address: zk://110.42.134.48:2181
  protocol:
    port: 20880
  scan:
    base-packages: cn.nanchaos.nim.service

mybatis-plus:
  global-config:
    db-config:
      id-type: auto