dubbo:
  application:
    name: nim-service
  registry:
    address: zk://ip:2181
  protocol:
    port: 20880
  scan:
    base-packages: cn.nanchaos.nim.service

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

spring:
  application:
    name: nim-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    url: jdbc:mysql://ip:port/nim